<?php
// =====================================================
//  HALF TIME PS AND CAFE — Setup Wizard
//  يفتح مرة واحدة بس عشان يعمل الداتابيز
// =====================================================

// منع التشغيل لو السيستيم شغال خلاص
if (file_exists(__DIR__ . '/config/database.php')) {
    $db_content = file_get_contents(__DIR__ . '/config/database.php');
    // لو فيه database.php حقيقي (مش sample) اسأل
}

$step    = 'form';
$error   = null;
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host   = trim($_POST['db_host']   ?? 'localhost');
    $user   = trim($_POST['db_user']   ?? 'root');
    $pass   = $_POST['db_pass']        ?? '';
    $dbname = trim($_POST['db_name']   ?? 'cafe_management');
    $appUrl = rtrim(trim($_POST['app_url'] ?? '/cafe'), '/');

    // جرب الاتصال بـ mysqli عشان multi_query
    try {
        $mysqli = new mysqli($host, $user, $pass);
        if ($mysqli->connect_error) {
            throw new Exception('فشل الاتصال: ' . $mysqli->connect_error);
        }
        $mysqli->set_charset('utf8mb4');

        // اعمل الداتابيز
        if (!$mysqli->query("CREATE DATABASE IF NOT EXISTS `{$dbname}` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")) {
            throw new Exception('فشل إنشاء قاعدة البيانات: ' . $mysqli->error);
        }
        if (!$mysqli->select_db($dbname)) {
            throw new Exception('فشل اختيار قاعدة البيانات: ' . $mysqli->error);
        }

        // قرا install.sql وشغّله بـ multi_query
        $sql = file_get_contents(__DIR__ . '/install.sql');
        if (!$sql) {
            throw new Exception('ملف install.sql مش موجود!');
        }

        // شغّل الـ SQL كاملاً دفعة واحدة
        if ($mysqli->multi_query($sql)) {
            // استنى كل الـ results تخلص
            do {
                if ($res = $mysqli->store_result()) {
                    $res->free();
                }
            } while ($mysqli->more_results() && $mysqli->next_result());
        }
        if ($mysqli->errno) {
            throw new Exception('خطأ في تنفيذ SQL: ' . $mysqli->error);
        }

        // تحقق إن الجداول اتعملت فعلاً
        $check = $mysqli->query("SELECT COUNT(*) AS c FROM information_schema.tables WHERE table_schema='{$dbname}' AND table_name='users'");
        $row   = $check ? $check->fetch_assoc() : ['c' => 0];
        if ((int)$row['c'] === 0) {
            throw new Exception('الجداول لم تُنشأ — تأكد من صحة install.sql');
        }
        $mysqli->close();

        // اكتب database.php
        $config = '<?php' . "\n";
        $config .= '// =====================================================' . "\n";
        $config .= '//  Database Configuration — generated by setup.php' . "\n";
        $config .= '// =====================================================' . "\n";
        $config .= "define('DB_HOST', " . var_export($host,   true) . ");\n";
        $config .= "define('DB_USER', " . var_export($user,   true) . ");\n";
        $config .= "define('DB_PASS', " . var_export($pass,   true) . ");\n";
        $config .= "define('DB_NAME', " . var_export($dbname, true) . ");\n\n";
        $config .= "define('APP_NAME', 'كافيه ماستر');\n";
        $config .= "define('APP_VERSION', '1.0');\n";
        $config .= "define('CURRENCY', 'ج.م');\n\n";
        $config .= "define('BASE_URL', " . var_export($appUrl, true) . ");\n\n";
        $config .= '// =====================================================' . "\n\n";
        $config .= 'function getDB(): PDO {' . "\n";
        $config .= '    static $pdo = null;' . "\n";
        $config .= '    if ($pdo !== null) return $pdo;' . "\n";
        $config .= '    try {' . "\n";
        $config .= '        $pdo = new PDO(' . "\n";
        $config .= "            'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4'," . "\n";
        $config .= '            DB_USER, DB_PASS,' . "\n";
        $config .= '            [' . "\n";
        $config .= '                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,' . "\n";
        $config .= '                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,' . "\n";
        $config .= '                PDO::ATTR_EMULATE_PREPARES   => false,' . "\n";
        $config .= '            ]' . "\n";
        $config .= '        );' . "\n";
        $config .= '    } catch (PDOException $e) {' . "\n";
        $config .= '        $isApi = defined(\'IS_API\') && IS_API;' . "\n";
        $config .= '        if ($isApi) { header(\'Content-Type: application/json; charset=utf-8\'); echo json_encode([\'success\'=>false,\'message\'=>\'خطأ في الاتصال بقاعدة البيانات\']); exit; }' . "\n";
        $config .= "        die('<div style=\"font-family:Cairo,Tahoma,sans-serif;direction:rtl;text-align:center;margin-top:100px;color:#c0392b\"><h2>⚠ خطأ في الاتصال بقاعدة البيانات</h2><p>يرجى التحقق من إعدادات الملف <code>config/database.php</code></p></div>');\n";
        $config .= '    }' . "\n";
        $config .= '    return $pdo;' . "\n";
        $config .= "}\n";

        file_put_contents(__DIR__ . '/config/database.php', $config);

        $success = true;
        $step    = 'done';

    } catch (Exception $e) {
        $error = $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>إعداد النظام — HALF TIME</title>
<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&display=swap" rel="stylesheet">
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'Cairo', Tahoma, sans-serif; background: #0f172a; color: #f1f5f9; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
.card { background: #1e293b; border-radius: 16px; padding: 40px; width: 100%; max-width: 500px; box-shadow: 0 25px 50px rgba(0,0,0,.5); }
.logo { text-align: center; margin-bottom: 30px; }
.logo-icon { font-size: 52px; display: block; margin-bottom: 8px; }
.logo h1 { font-size: 22px; font-weight: 800; color: #f59e0b; }
.logo p { font-size: 13px; color: #94a3b8; margin-top: 4px; }
label { display: block; font-size: 13px; font-weight: 600; color: #cbd5e1; margin-bottom: 6px; margin-top: 18px; }
input { width: 100%; padding: 12px 16px; border-radius: 8px; border: 1px solid #334155; background: #0f172a; color: #f1f5f9; font-family: 'Cairo', Tahoma, sans-serif; font-size: 14px; direction: ltr; text-align: left; }
input:focus { outline: none; border-color: #f59e0b; }
.hint { font-size: 11px; color: #64748b; margin-top: 4px; }
.btn { width: 100%; margin-top: 28px; padding: 14px; background: #f59e0b; color: #0f172a; border: none; border-radius: 10px; font-family: 'Cairo', Tahoma, sans-serif; font-size: 16px; font-weight: 700; cursor: pointer; transition: background .2s; }
.btn:hover { background: #d97706; }
.alert-error { background: #450a0a; border: 1px solid #ef4444; border-radius: 10px; padding: 14px 16px; margin-bottom: 20px; color: #fca5a5; font-size: 14px; }
.done-icon { font-size: 64px; text-align: center; display: block; margin-bottom: 16px; }
.done-title { text-align: center; font-size: 24px; font-weight: 800; color: #4ade80; margin-bottom: 8px; }
.done-sub { text-align: center; font-size: 14px; color: #94a3b8; margin-bottom: 28px; }
.links { display: flex; gap: 12px; flex-direction: column; }
.link-btn { display: block; text-align: center; padding: 12px; border-radius: 10px; font-weight: 700; font-size: 15px; text-decoration: none; }
.link-admin { background: #f59e0b; color: #0f172a; }
.link-cashier { background: #1d4ed8; color: #fff; }
.link-btn:hover { opacity: .9; }
.info-box { background: #0f172a; border-radius: 8px; padding: 12px 16px; margin-top: 20px; font-size: 12px; color: #64748b; border: 1px solid #1e293b; }
.info-box span { color: #94a3b8; }
</style>
</head>
<body>
<div class="card">

  <div class="logo">
    <span class="logo-icon">☕</span>
    <h1>HALF TIME PS AND CAFE</h1>
    <p>معالج الإعداد — Setup Wizard</p>
  </div>

  <?php if ($step === 'form'): ?>

    <?php if ($error): ?>
    <div class="alert-error">⚠ <?= htmlspecialchars($error) ?></div>
    <?php endif; ?>

    <form method="post">
      <label>MySQL Host</label>
      <input type="text" name="db_host" value="localhost" required>
      <div class="hint">عادةً localhost</div>

      <label>اسم المستخدم (Username)</label>
      <input type="text" name="db_user" value="root" required>

      <label>كلمة المرور (Password)</label>
      <input type="password" name="db_pass" placeholder="اتركها فارغة لو مفيش password">
      <div class="hint">WAMP: فارغة عادةً | XAMPP: فارغة عادةً</div>

      <label>اسم قاعدة البيانات</label>
      <input type="text" name="db_name" value="cafe_management" required>

      <label>مسار السيستيم (Base URL)</label>
      <input type="text" name="app_url" value="/cafe" required>
      <div class="hint">لو المجلد اسمه cafe اتركه /cafe</div>

      <button type="submit" class="btn">🚀 تثبيت النظام</button>
    </form>

    <div class="info-box">
      <span>هيعمل:</span> إنشاء قاعدة البيانات ← تنفيذ install.sql ← كتابة config/database.php
    </div>

  <?php elseif ($step === 'done'): ?>

    <span class="done-icon">✅</span>
    <div class="done-title">تم التثبيت بنجاح!</div>
    <div class="done-sub">قاعدة البيانات جاهزة والسيستيم شغال</div>

    <div class="links">
      <a href="<?= htmlspecialchars($appUrl ?? '/cafe') ?>/admin" class="link-btn link-admin">
        لوحة الأدمن ←
      </a>
      <a href="<?= htmlspecialchars($appUrl ?? '/cafe') ?>/cashier" class="link-btn link-cashier">
        واجهة الكاشير ←
      </a>
    </div>

    <div class="info-box" style="margin-top:20px;color:#ef4444">
      ⚠ <span style="color:#ef4444">احذف ملف setup.php بعد التثبيت عشان الأمان</span>
    </div>

  <?php endif; ?>

</div>
</body>
</html>
